import pandas as pd

df = pd.read_csv('twitter_multi_class_sentiment.csv')
print('---------------head-----------------')
print(df.head())
print('---------------columns-----------------')
print(df.columns)
print('---------------shape-----------------')
print(df.shape)
print('---------------info-----------------')
print(df.info())
print('---------------df-----------------')
print(df)
print('---------------describe-----------------')
print(df.describe())
print('---------------isnull().sum()-----------------')
print(df.isnull().sum())
print('---------------label value counts-----------------')
print(df['label'].value_counts())